services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # AMQP protocol
      - "15672:15672"   # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq_admin_user
      RABBITMQ_DEFAULT_PASS: bg0mXyNAOD1vay8VP
    networks:
      - rabbitmq_net

  # Example service that can use RabbitMQ
  # Uncomment to test inter-container communication
  # app:
  #   build: .
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - rabbitmq_net
  #   environment:
  #     RABBITMQ_URL: amqp://rabbitmq_admin_user:bg0mXyNAOD1vay8VP@rabbitmq:5672/

networks:
  rabbitmq_net:
    driver: bridge
